# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        default:
            toolbar: 'full'
            extraPlugins: 'codesnippet'
            codeSnippet_theme: 'default'
    plugins:
        codesnippet:
            path: 'bundles/fosckeditor/plugins/codesnippet/'
            filename: 'plugin.js'
